// unwanted-domains.js

const unwantedDomains = [
  // Báo lá cải, tin giải trí
  "2sao.vn",
  "24h.com.vn",
  "afamily.vn",
  "baomoi.com",
  "chuyentrang.baotintuc.vn",
  "docbao.vn",
  "eva.vn",
  "giadinhvaphapluat.vn",
  "kenh14.vn",
  "mientrungtoday.com",
  "motthegioi.vn",
  "ngoisao.vn",
  "phununews.vn",
  "saostar.vn",
  "soha.vn",
  "tamsugiadinh.vn",
  "thethaovanhoa.vn",
  "tienphong.vn",
  "tintuc.vn",
  "tinmoi.vn",
  "tintuconline.com.vn",
  "tiin.vn",
  "vietgiaitri.com",
  "yeah1.com",

  // Mạng xã hội, video, cache
  "chat.zalo.me",
  "facebook.com",
  "google.com",
  "linkedin.com",
  "tiktok.com",
  "webcache.googleusercontent.com",
  "youtube.com",
  "zalo.me",

  // Trang tuyển dụng, việc làm, freelancer
  "careerbuilder.vn",
  "careerlink.vn",
  "freelancervietnam.vn",
  "glints.com",
  "mywork.com.vn",
  "timviecnhanh.com",
  "topcv.vn",
  "vieclam24h.vn",
  "vietnamworks.com",

  // Trang luật, tư vấn pháp luật
  "baophapluat.vn",
  "congly.vn",
  "luatduonggia.vn",
  "luathoangsa.vn",
  "luathungson.vn",
  "luatsu.vn",
  "luatvietan.vn",
  "luatvietnam.vn",
  "luatvn.vn",
  "phapluatnet.vn",
  "phapluatplus.vn",
  "phapluatxahoi.kinhtedothi.vn",
  "thuvienphapluat.vn",

  // Trang vàng, directory, dịch vụ
  "hbcg.vn",
  "maisonoffice.vn",
  "top10tphcm.com",
  "toplist.vn",
  "trangvangtructuyen.vn",
  "trangvangvietnam.com",
  "tuvanquangminh.com",
  "yellowpages.vn",

  // Giáo dục, học tập, tài liệu
  "123doc.net",
  "cafedu.vn",
  "diadiemthi.edu.vn",
  "giaoduc.net.vn",
  "giasudatviet.com",
  "hotrovn.edu.vn",
  "ielts-fighter.com",
  "international-schools.org",
  "timhieuhocvien.edu.vn",
  "truonghoc.violet.vn",
  "tuyensinh247.com",
  "tuyensinhso.vn",
  "vnedu.vn",
  "vietschool.vn",

  // Du học
  "aptechvietnam.edu.vn",
  "duhoc24h.vn",
  "duhocuk.edu.vn",
  "duhocnet.vn",
  "duhoctms.edu.vn",
  "duhocviet.com",
  "duhocvietphap.com",
  "duhocvietnam.edu.vn",
  "edutop.vn",
  "edunavi.vn",
  "tuvan.duhocmy.vn",
  "vied.vn",
  "vietnamstudyabroad.edu.vn",
  "vschool.edu.vn",

  // Mua bán online
  "adayroi.com",
  "cellphones.com.vn",
  "chotot.com",
  "concung.com",
  "dienmayxanh.com",
  "fptshop.com.vn",
  "hotdeal.vn",
  "lazada.vn",
  "mediamart.vn",
  "muaban.net",
  "phongvu.vn",
  "sendo.vn",
  "shopee.vn",
  "thegioididong.com",
  "tiki.vn",
  "vanggia.com",
  "yes24.vn",

  // Trang tin tức chính thống (nếu loại tổ chức nhà nước)
  "baocaovien.vn",
  "baochinhphu.vn",
  "baodauthau.vn",
  "baodautu.vn",
  "cand.com.vn",
  "congthuong.vn",
  "dantri.com.vn",
  "laodong.vn",
  "nhandan.vn",
  "plo.vn",
  "quochoi.vn",
  "suckhoedoisong.vn",
  "thanhnien.vn",
  "thanhnienviet.vn",
  "toquoc.vn",
  "tuoitre.vn",
  "viettimes.vn",
  "vietnamnet.vn",
  "vnexpress.net",
  "vov.vn",
  "vtv.vn",
  "vneconomy.vn",

  // Báo ngành, tổ chức nhà nước
  "baoquankhu7.vn",
  "cafebiz.vn",
  "cafef.vn",
  "finance.vietstock.vn",
  "ketoananpha.vn",
  "lifestyle.znews.vn",
  "moc.gov.vn",
  "thitruongtaichinhtiente.vn",
  "tripadvisor.com.vn",
  "vietnamreport.net.vn",
  "vnr500.com.vn",

  // Diễn đàn, blog, review
  "blogspot.com",
  "chontotnhat.com",
  "diendan.org",
  "diendanbaclieu.net",
  "diendankinhte.vn",
  "lamchame.com",
  "otofun.net",
  "reviewdao.vn",
  "reviewsanpham.net",
  "reviewtop.vn",
  "topnlist.com",
  "tinhte.vn",
  "vn-zoom.org",
  "vnreview.vn",
  "voz.vn",
  "websosanh.vn",
  "webtretho.com",
  "wordpress.com",

  // Wikipedia, từ điển
  "vi.wiktionary.org",
  "wikipedia.org",
  "vi.wikipedia.org",

  // Cổng thông tin công + công ty, trường học, nhà hàng...
  "booking.com",
  "foody.vn",
  "homedy.com",
  "ivivu.com",
  "momo.vn",
  "riviu.vn",
  "traveloka.com",

  // Đài truyền hình địa phương
  "bna.gov.vn",
  "btd.vn",
  "canthotv.vn",
  "danangtv.vn",
  "haitv.vn",
  "hanoitv.vn",
  "htv.com.vn",
  "khanhhoatv.vn",
  "nghean.gov.vn",
  "qntv.vn",
  "thanhhoatv.vn",
  "ththtv.vn",
  "vtv.vinhphuc.gov.vn",

  // Chính phủ
  "chinhphu.vn",
  "tphcm.chinhphu.vn",
  "xaydungchinhsach.chinhphu.vn",

  // Báo tỉnh (được gom nhóm riêng nếu cần tách sau)
  "baobacgiang.com.vn",
  "baobackan.org.vn",
  "baobaclieu.vn",
  "baobacninh.com.vn",
  "baobinhdinh.vn",
  "baobinhduong.vn",
  "baobinhphuoc.com.vn",
  "baobinhthuan.com.vn",
  "baocamau.vn",
  "baocaobang.vn",
  "baocantho.com.vn",
  "baodaklak.vn",
  "baodaknong.org.vn",
  "baodienbienphu.info.vn",
  "baodongnai.com.vn",
  "baodongthap.vn",
  "baogialai.com.vn",
  "baohagiang.vn",
  "baohai.duong.gov.vn",
  "baohaiquan.vn",
  "baohaugiang.com.vn",
  "baohatinh.vn",
  "baohcm.com.vn",
  "baohungyen.vn",
  "baokhanhhoa.vn",
  "baokiengiang.vn",
  "baokontum.com.vn",
  "baolaichau.vn",
  "baolangson.vn",
  "baolamdong.vn",
  "baolongan.vn",
  "baonamdinh.vn",
  "baonghean.vn",
  "baoninhbinh.org.vn",
  "baoninhthuan.com.vn",
  "baophutho.vn",
  "baophuyen.com.vn",
  "baoquangbinh.vn",
  "baoquangnam.vn",
  "baoquangngai.vn",
  "baoquangninh.com.vn",
  "baoquangtri.vn",
  "baosoctrang.org.vn",
  "baosonla.org.vn",
  "baotayninh.vn",
  "baothaibinh.com.vn",
  "baothainguyen.vn",
  "baothanhhoa.vn",
  "baothuathienhue.vn",
  "baotiengiang.vn",
  "baotravinh.vn",
  "baotuyenquang.com.vn",
  "baovinhlong.com.vn",
  "baovinhphuc.com.vn",
  "baoyenbai.com.vn",

  // Khác
  "masothue.com",
  "quocluat.vn",
  "tuvanhuonglan.vn",
  "viettelconstruction.com.vn",

  // -------- Tư vấn tài chính, kinh tế --------
  "taichinhplus.vn",
  "tapchitaichinh.vn",
  "vietnamfinance.vn",
  "tinnhanhchungkhoan.vn",
  "thoibaotaichinhvietnam.vn",
  "thoibaonganhang.vn",
  "ndh.vn",
  "vietstock.vn",
  "vietstockfinance.com.vn",
  "vietfin.vn",
  "doanhnhansaigon.vn",
  "saigondautu.com.vn",
  "vneconomy.vn", // Đã có – giữ nguyên nếu cần
  "dautubds.com.vn",
  "daututaichinh.net",
  "evnfinance.com.vn",

  // -------- Tư vấn pháp luật, luật sư --------
  "tuvanphapluat.vn",
  "tuvanluat.vn",
  "tuvanluatdaiviet.com.vn",
  "tuvanvietluat.com",
  "tuvanluathungthang.com",
  "tuvanphapluatmienphi.net",
  "luatbaoan.vn",
  "luatsuhcm.vn",
  "luatvietphong.vn",
  "vanbanphapluat.co",
  "luatminhgia.com.vn",
  "vanphongluatsutoanquoc.com",
  "tuvan.luatvietnam.vn",

  // -------- Tư vấn kinh tế, doanh nghiệp --------
  "vietnambiz.vn",
  "enternews.vn",
  "khoinghiep.org.vn",
  "khoinghieptre.vn",
  "doanhnghiephoinhap.vn",
  "diendandoanhnghiep.vn",
  "ketoanleanh.vn",
  "vietq.vn",
  "vibonline.com.vn", // Diễn đàn kinh tế
  "ktdt.vn",
  "kinhtevadubao.vn",
  "vccinews.vn", // Phòng Thương mại và Công nghiệp
  "vietrade.gov.vn", // Cục xúc tiến thương mại
  "vietnammarcom.edu.vn", // Tư vấn thương hiệu - kinh doanh

  // -------- Tư vấn bảo hiểm, hưu trí, sức khỏe tài chính --------
  "baohiemxahoi.gov.vn",
  "tuvanbaohiem.vn",
  "tuvanbaohiem.net",
  "hanhtrinhvuive.com.vn",
  "baohiempo.vn",
  "baohiemtoanmy.com",
  "lifehub.vn",
  "smartpay.com.vn",

  // -------- Tư vấn đầu tư bất động sản tài chính --------
  "batdongsan.com.vn",
  "cafeland.vn",
  "diaoconline.vn",
  "alonhadat.com.vn",
  "nha.chotot.com",
  "tinbatdongsan.com",
  "thitruong.today",
  "rever.vn",
  "cenhomes.vn",
  "propzy.vn",

  // -------- Các nền tảng cung cấp dịch vụ tư vấn tài chính cá nhân --------
  "moneylover.me",
  "finsify.com",
  "finhay.com.vn",
  "vndirect.com.vn",
  "tcbs.com.vn",
  "miraeasset.com.vn",
  "ssi.com.vn",
  "vps.com.vn",
  "acbs.com.vn",
  "mbs.com.vn",
  "vnsc.com.vn",
  "zalopay.vn",
  "klook.com",
  "xanhsm.com",
  // Thanh toán online
  "momo.vn",
  "vnpay.vn",
  "onepay.vn",
  "nganluong.vn",
  "baokim.vn",
  "vimo.vn",
  "payoo.vn",
  "viettelmoney.vn",
  "vinid.net",
  "shopeepay.vn",
  "airpay.vn",
  "tpbank.vn",
  "bidvsmartbanking.vn",
  "vpbankonline.vn",
  //Trang quảng cáo
  "ads.google.com",
  "facebook.com/business/ads",
  "zalo.me/ads",
  "tiktok.com/business",
  "admicro.vn",
  "chiasequangcao.com",
  "cpas.vn",
  "coccoc.com/ads",
  "adflex.vn",
  "masoffer.com",
  "ecomobi.com",
  "accesstrade.vn",
  "haravan.com",
  "ladipage.vn",
  "bizfly.vn",
  //Trang games
  "gamek.vn",
  "motgame.vn",
  "kenh14.vn/game",
  "24h.com.vn/game",
  "vng.com.vn",
  "zingplay.vn",
  "gamelandvn.com",
  "cafegame.tv",
  "y8.com",
  "miniclip.com",
  "crazygames.com",
  "kongregate.com",
  "roblox.com",
  "epicgames.com",
  "steampowered.com",
  "addictinggames.com",
  "armorgames.com",
  "poki.com",
  "agame.com",
  "newgrounds.com",
  //Xem phim nghe nhạc
  "nhaccuatui.com",
  "zingmp3.vn",
  "spotify.com",
  "youtube.com",
  "soundcloud.com",
  "tiktok.com",
  "vieon.vn",
  "vtvgo.vn",
  "danet.vn",
  "fptplay.vn",
  "tv360.vn",
  "cliptv.vn",
  "mytv.com.vn",
  "galaxycine.vn",
  "phimmoi.net",
  "bilutv.zing.vc",
  "hdviet.com",
  "wetv.vip",
  "iq.com",
  "netflix.com",
  //Other
  "languages.oup.com",
  "vincom.com.vn",
  "pasgo.vn",
  "melamine.vn",
  "kichcaudulichtphcm.vn",
  "cuongdulich.com",
  "vinwonders.com",
  "phongcachmoc.vn",
  "www.bachhoaxanh.com",
  "www.anninhthudo.vn",
  "anninhthudo.vn",
  "thegioitiepthi.danviet.vn",
  "banhtranggiangmy.com",
  "dulichnewtour.vn",
  "elitetour.com.vn",
  "znews.vn",
  "thegioihaisan.vn",
  "www.nhahangbepkhoi.com",
  "www.instagram.com",
  "www.sggp.org.vn",
  "khoahocphothong.vn",
  // Khoa học
  "khoahoc.tv",
  "khoahocphattrien.vn",
  "vnexpress.net/khoa-hoc",
  "dantri.com.vn/khoa-hoc",
  "vietnamnet.vn/khoa-hoc",
  "science.org",
  "nature.com",
  "sciencedaily.com",
  "nasa.gov",
  "livescience.com",
  // Phong thủy
  "phongthuyso.vn",
  "xemtuong.net",
  "tuviso.com",
  "lichngaytot.com",
  "thienmenh.net",
  "phongthuyvuong.com",
  "tuvi.vn",
  "tuvi247.com",
  "xemboi.com.vn",
  "thanglongdaoquan.vn",
  //Other
  "congan.com.vn",
  "mytour.vn",
  "www.nguyenkim.com",
  "shamoji.vn",
  "tiemtrariri.com",
  "www.hoteldesartssaigon.com",
  "justfly.vn",
  "sofitel-saigon-plaza.com",
  "menuonline.vn",
  "melisacenter.v",
  "aeonmall-binhtan.com.vn",
  "thaiexpress.vn",
  "diachiamthuc.vn",
  "gia-hanoi.com",
  "saigonamthuc.vn",
  "nhahangngon.com.vn",
  "nhahangmonanngon.vn",
  "mia.vn",
  "www.sapo.vn",
  "thienbinhgroup.com",
  "hanoimoi.vn",
  "ezcloud.vn",
  "www.hutech.edu.vn",
  "skylightnhatrang.com",
  "nhahangchotinhsapa.vn",
  "www.cet.edu.vn",
  "balancedecor.com.vn",
  "canthotourism.vn",
  "hotelduparchanoi.com",
  "longhau.com.vn",
  "careerviet.vn",
  "congchungnguyenhue.com",
  "baovephapluat.vn",
  "vtcnews.vn",
  "agoda.com",
  "vn.trip.com",
  "nguoiquansat.vn",
  "trivago.vn",
  "nld.com.vn",
  "vn.jcb",
  "vietnamplus.vn",
  "kiemsat.vn",
  "baovanhoa.vn",
  "vietnam.vn",
  "khachsan.chudu24.com",
  "www.bestprice.vn",
  "skyscanner.com.vn",
  "vietnam.travel",
  "vietnamtourism.gov.vn",
  "travel.com.vn",
  "dulichviet.com.vn",
  "fiditour.com",
  "datviettour.com.vn",
  "vntrip.vn",
  "khamphadisan.com",
  "phuot.vn",
  "skyhotel.vn",
  "www.expedia.com.vn",
  "www.pexels.com",
  "www.dnse.com.vn",
  "63stravel.com",
  "www.hoteljob.vn",
  "kiddihub.com",
  "esearch.vn",
  "vietjack.com",
  "moon.vn",
  "olm.vn",
  "cunghoc.vn",
  "applyzones.com",
  "duhoc.vietnamnet.vn",
  "duhocvietphuong.edu.vn",
  "duhocnhatban.edu.vn",
  "duhoctoancau.com",
  "duhocinec.com",
  "huongnghiep.hocmai.vn",
  "vnur.vn",
  "careerfinder.vn",
  "kenhtuyensinh.vn",
  "timviec365.vn/huong-nghiep",
  "timtruongquocte.com",
  "giaoducthoidai.vn",
  "congbao.binhphuoc.gov.vn",
  "baohaiduong.vn",
];

module.exports = unwantedDomains;
